import copy
import random
import argparse
import obj_transformation as trans
from logger import CLogger
from config.config import Config
from utils.v2x_object import V2XInfo


def rq1_vis_parser():
    parser = argparse.ArgumentParser(description="rq1 command")
    parser.add_argument('-t', '--transform',
                        help="select a transform operation, insert/delete/translation/scaling/rotation")
    parser.add_argument('-s', '--scene', help="the scene of dataset", default=1)
    args = parser.parse_args()
    return args


def rq1_vis(transformation='insert', scene=1):
    """
    Visualize and display all scenario data generated by the v2xgen and baseline methods.

    :param transformation: insert, delete, scale, translation and rotation
    :param scene: 1-9 scenes
    :return:
    """
    dataset_config = Config(scene=scene)
    begin_index = dataset_config.begin_index
    data_num = dataset_config.scene_data_num

    select_data_num = dataset_config.select_data_num

    # 帧遍历：在指定的背景帧范围内循环。
    for bg_index in range(1, select_data_num + 1):
        if bg_index < begin_index:
            continue
        elif bg_index > data_num + begin_index:
            break

        CLogger.info(f"Background {bg_index}")

        # load vehicle info
        # 为每一帧创建 ego_info 和 cp_info 对象（代表 V2XGen 组）
        ego_info = V2XInfo(bg_index, dataset_config=dataset_config)
        cp_info = V2XInfo(bg_index, is_ego=False, dataset_config=dataset_config)
        # 使用 copy.deepcopy 创建完全一致的 baseline 副本（代表 Baseline 组）
        ego_info_baseline = copy.deepcopy(ego_info)
        cp_info_baseline = copy.deepcopy(cp_info)

        # random select car 
        # 从当前帧已有的车辆中随机选出一个 car_id（除插入操作外，其余操作都需要指定目标车）
        car_id = random.choice(list(ego_info.vehicles_info.keys()))

        if transformation == 'insert':
            # same background as baseline
            trans.vehicle_insert(ego_info, cp_info, ego_info_baseline, cp_info_baseline)
        elif transformation == 'delete':
            # same bg data and car_id as baseline
            trans.vehicle_delete(ego_info, cp_info, ego_info_baseline, cp_info_baseline, car_id)
        elif transformation == 'translation':
            # same bg data, car_id and translation param as baseline
            trans.vehicle_translation(ego_info, cp_info, ego_info_baseline, cp_info_baseline, car_id)
        elif transformation == 'scaling':
            # same bg data, car_id and scaling rate as baseline
            trans.vehicle_scaling(ego_info, cp_info, ego_info_baseline, cp_info_baseline, car_id)
        elif transformation == 'rotation':
            # same bg data, car_id and rot degree as baseline
            trans.vehicle_rotation(ego_info, cp_info, ego_info_baseline, cp_info_baseline, car_id)


if __name__ == '__main__':
    cmd_args = rq1_vis_parser()
    rq1_vis(cmd_args.transform, int(cmd_args.scene))
